=== tavisreddick/oer-vector-library/Transformations/personComponents.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
	targetNamespace="http://www.sleepingdog.org.uk/oer-vector-library/person-components"
	xmlns="http://www.sleepingdog.org.uk/oer-vector-library/person-components">
	<xs:simpleType name="angleDegrees">
		<xs:restriction base="xs:short">
			<xs:minInclusive value="-359"/>
			<xs:maxInclusive value="359"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="designation">
		<xs:restriction base="xs:string">
			<xs:enumeration value="left"/>
			<xs:enumeration value="right"/>
			<xs:enumeration value="upper"/>
			<xs:enumeration value="lower"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="symmetryOperation">
		<xs:restriction base="xs:string">
			<xs:enumeration value="flip-horizontal"/>
			<xs:enumeration value="flip-vertical"/>
			<xs:enumeration value="rotate"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="personComponents">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="component" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="twin" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:attribute name="id" use="required" />
									<xs:attribute name="symmetry" use="required" type="symmetryOperation" />
									<xs:attribute name="axis" use="optional" type="angleDegrees" />
									<xs:attribute name="x" use="optional" type="xs:short" />
									<xs:attribute name="y" use="optional" type="xs:short" />
									<xs:attribute name="designation" use="required" type="designation" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" />
						<xs:attribute name="designation" use="optional" type="designation" />
						<xs:attribute name="ball" use="optional" type="xs:NMTOKEN" />
						<xs:attribute name="socket" use="optional" type="xs:NMTOKEN" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== tavisreddick/oer-vector-library/Transformations/personComponents.xml
<?xml version="1.0" encoding="UTF-8"?>
<personComponents xmlns="http://www.sleepingdog.org.uk/oer-vector-library/person-components"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.sleepingdog.org.uk/oer-vector-library/person-components personComponents.xsd">
	<component id="person-1-front-arms-right-hand" designation="right">
		<twin id="person-1-front-arms-left-hand" symmetry="flip-horizontal" x="150" designation="left" />
	</component>
	<component id="person-1-front-arms-right-lower" designation="right">
		<twin id="person-1-front-arms-left-lower" symmetry="flip-horizontal" x="150" designation="left"/>
	</component>
	<component id="person-1-front-arms-right-upper" designation="right">
		<twin id="person-1-front-arms-left-upper" symmetry="flip-horizontal" x="150" designation="left"/>
	</component>
	<component id="person-1-front-legs-right-foot" designation="right">
		<twin id="person-1-front-legs-left-foot" symmetry="flip-horizontal" x="150" designation="left"/>
	</component>
	<component id="person-1-front-legs-right-lower" designation="right">
		<twin id="person-1-front-legs-left-lower" symmetry="flip-horizontal" x="150" designation="left"/>
	</component>
	<component id="person-1-front-legs-right-upper" designation="right">
		<twin id="person-1-front-legs-left-upper" symmetry="flip-horizontal" x="150" designation="left"/>
	</component>
	<component id="person-2-front-arms-right-hand" designation="right">
		<twin id="person-2-front-arms-left-hand" symmetry="flip-horizontal" x="150" designation="left" />
	</component>
	<component id="person-2-front-arms-right-lower" designation="right">
		<twin id="person-2-front-arms-left-lower" symmetry="flip-horizontal" x="150" designation="left"/>
	</component>
	<component id="person-2-front-arms-right-upper" designation="right">
		<twin id="person-2-front-arms-left-upper" symmetry="flip-horizontal" x="150" designation="left"/>
	</component>
	<component id="person-2-front-legs-right-foot" designation="right">
		<twin id="person-2-front-legs-left-foot" symmetry="flip-horizontal" x="150" designation="left"/>
	</component>
	<component id="person-2-front-legs-right-lower" designation="right">
		<twin id="person-2-front-legs-left-lower" symmetry="flip-horizontal" x="150" designation="left"/>
	</component>
	<component id="person-2-front-legs-right-upper" designation="right">
		<twin id="person-2-front-legs-left-upper" symmetry="flip-horizontal" x="150" designation="left"/>
	</component>
</personComponents>
